Convert scripts to mksh compliant
Signed-off-by: shadichy <hotrobb360web@gmail.com>

diff --git a/etc/scripts/iptsd-foreach b/etc/scripts/iptsd-foreach
--- a/etc/scripts/iptsd-foreach
+++ b/etc/scripts/iptsd-foreach
@@ -1,27 +1,29 @@
-#!/bin/bash
+#!/system/bin/sh
+# shellcheck shell=ksh
 # SPDX-License-Identifier: GPL-2.0-or-later
 
-set -euo pipefail
+if [ ! "$SCRIPT_DIR" ]; then
+	SCRIPT_DIR=$(dirname "$(realpath "$0")")
+	export SCRIPT_DIR
+fi
 
-function spdlog() {
-	local level="${1}" messages=("${@:2}")
+set -uo pipefail
+
+spdlog() {
+	local level="${1}"
+	shift
+	local messages="$*"
 
 	case "${level}" in
-	info)
-		level="$(printf "%s%s%s" "\033[32m" "info" "\e[0m")"
-		;;
-	warn)
-		level="$(printf "%s%s%s" "\033[33m\033[1m" "warning" "\e[0m")"
-		;;
-	error)
-		level="$(printf "%s%s%s" "\033[31m\033[1m" "error" "\e[0m")"
-		;;
+	info) level="$(printf "%s%s%s" "\033[32m" "info" "\e[0m")" ;;
+	warn) level="$(printf "%s%s%s" "\033[33m\033[1m" "warning" "\e[0m")" ;;
+	error) level="$(printf "%s%s%s" "\033[31m\033[1m" "error" "\e[0m")" ;;
 	esac
 
-	echo -e "[$(date '+%H:%M:%S.%3N')] [${level}]" "${messages[@]}" >&2
+	echo -e "[$(date '+%H:%M:%S.%3N')] [${level}]" "${messages}" >&2
 }
 
-function print-if-executable() {
+print_if_executable() {
 	local file="${1}"
 
 	if [ -x "${file}" ]; then
@@ -32,26 +34,27 @@ function print-if-executable() {
 	return 1
 }
 
-function find-program() {
+find_program() {
 	local name="${1}" script_dir="${2}" project_dir="${3:-}"
 
-	# If the calling script is installed to /usr, the program should be right next to it
-	if print-if-executable "${script_dir}/${name}"; then
+	# If the calling script is installed to $PATH, the program should be right next to it
+	if print_if_executable "${script_dir}/${name}"; then
 		return 0
 	fi
 
 	# Otherwise the script might be called from the cloned git repository
 	if [ -n "${project_dir}" ] && [ -f "${project_dir}/meson_options.txt" ]; then
-		local -r file="$(find "${project_dir}" -type f -executable -name "${name}" | head -n1)"
+		local file
+		file="$(find "${project_dir}" -type f -executable -name "${name}" | head -n1)"
 
-		if print-if-executable "${file}"; then
+		if print_if_executable "${file}"; then
 			spdlog info "Located ${name} at ./$(realpath --relative-to="${PWD}" "${file}")"
 			return 0
 		fi
 	fi
 
 	# Fall back to looking in PATH
-	if print-if-executable "$(command -v "${name}" || true)"; then
+	if print_if_executable "$(command -v "${name}" || true)"; then
 		spdlog warn "Located ${name} using PATH"
 		spdlog warn "This script is designed to not use PATH, something might be wrong"
 		return 0
@@ -60,9 +63,9 @@ function find-program() {
 	return 1
 }
 
-function run-iptsd-foreach() {
-	local -r script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
-	local -r project_dir="$(realpath "${script_dir}/../..")"
+run_iptsd_foreach() {
+	local project_dir
+	project_dir="$(realpath "${SCRIPT_DIR}/../..")"
 
 	local device_index=""
 	local device_type="any"
@@ -72,28 +75,17 @@ function run-iptsd-foreach() {
 
 	while getopts ":t:i:pmh" args; do
 		case "${args}" in
-		i)
-			device_index="${OPTARG}"
-			;;
-		t)
-			device_type="${OPTARG}"
-			;;
-		p)
-			xargs_procs="0"
-			;;
-		m)
-			xargs_procs="0"
-			tmux_socket="$(mktemp -u)"
-			;;
-		*)
-			show_help="1"
-			;;
+		i) device_index="${OPTARG}" ;;
+		t) device_type="${OPTARG}" ;;
+		p) xargs_procs="0" ;;
+		m) xargs_procs="0" && tmux_socket="$(mktemp -u)" ;;
+		*) show_help="1" ;;
 		esac
 	done
 
 	shift $((OPTIND - 1))
 
-	if (("$#" == 0)); then
+	if [ "$*" = "" ]; then
 		show_help="1"
 	fi
 
@@ -119,16 +111,18 @@ function run-iptsd-foreach() {
 		return 1
 	fi
 
-	local -r check_device="$(find-program "iptsd-check-device" "${script_dir}" "${project_dir}")"
+	local check_device
+	check_device="$(find_program "iptsd-check-device" "${SCRIPT_DIR}" "${project_dir}")"
 
 	if [ -z "${check_device}" ]; then
 		spdlog error "Could not locate iptsd-check-device"
 		return 1
 	fi
 
-	local devices=()
+	local devices
+	devices=()
 
-	while read -rd $'\n' device; do
+	while read -r device; do
 		if [ ! -r "${device}" ]; then
 			spdlog warn "Can't read from ${device}, is the program running as root?"
 			continue
@@ -138,17 +132,17 @@ function run-iptsd-foreach() {
 			continue
 		fi
 
-		devices+=("${device}")
+		devices+=("$device")
 	done <<<"$(find /dev -maxdepth 1 | grep -E "hidraw[0-9]+" | sort)"
 
 	# If no devices were found, exit
-	if (("${#devices[@]}" == 0)); then
+	if [ ! "${devices[@]}" ]; then
 		spdlog info "No devices found"
 		return 0
 	fi
 
 	if [ -n "${device_index}" ]; then
-		if (("${#devices[@]}" <= "${device_index}")) || (("${device_index}" < 0)); then
+		if ((${#devices[@]} <= device_index)) || ((device_index < 0)); then
 			spdlog error "Device index is out of range"
 			return 1
 		fi
@@ -157,11 +151,12 @@ function run-iptsd-foreach() {
 	fi
 
 	# Ignore the tmux option if there is only one device
-	if (("${#devices[@]}" == 1)); then
+	if ((${#devices[@]} == 1)); then
 		tmux_socket=""
 	fi
 
-	local xargs_cmd=("bash" "-c" "$*")
+	local xargs_cmd
+	xargs_cmd=("bash" "-c" "$*")
 
 	if [ -n "${tmux_socket}" ]; then
 		xargs_cmd=("tmux" "-S" "${tmux_socket}" "new-window" "-n" "{}" "${xargs_cmd[@]}")
@@ -169,7 +164,8 @@ function run-iptsd-foreach() {
 	fi
 
 	# Save existing traps
-	local -r saved_traps="$(trap)"
+	local saved_traps
+	saved_traps="$(trap)"
 
 	# Ignore SIGINT and SIGTERM, these have to be handled by xargs / iptsd
 	trap -- "" SIGINT
@@ -193,6 +189,4 @@ function run-iptsd-foreach() {
 	return 0
 }
 
-if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
-	run-iptsd-foreach "$@"
-fi
+run_iptsd_foreach "$@"
